# These are supported funding model platforms

github: [KhanyadDlamini]            # GitHub Sponsors
patreon:                            # (leave empty if not using Patreon)
open_collective: khanyakwezwe-dlamini     # Open Collective username
ko_fi: Khanyakwezwe                # Ko-fi username
tidelift:                            # (leave empty if not using Tidelift)
community_bridge:                     # (leave empty if not using Community Bridge)
liberapay:                            # (leave empty if not using Liberapay)
issuehunt:                            # (leave empty if not using IssueHunt)
lfx_crowdfunding:                     # (leave empty if not using LFX Crowdfunding)
polar:                                # (leave empty if not using Polar)

